# Security OAuth
spring:
  security:
    oauth2.client:
      registration:
        google:
          clientId: "${GOOGLE_CLIENT_ID}"
          clientSecret: "${GOOGLE_CLIENT_SECRET}"
          scope:
            - email
            - profile
        kakao:
          clientId: "${KAKAO_CLIENT_ID}"
          clientSecret: "${KAKAO_CLIENT_SECRET}"
          clientAuthenticationMethod: post
          authorizationGrantType: authorization_code
          redirectUri: "localhost:8080/login/oauth2/code/kakao"
          scope:
            - profile_nickname
            - profile_image
            - account_email
          clientName: Kakao
      # Provider 설정
      provider:
        kakao:
          authorizationUri: https://kauth.kakao.com/oauth/authorize
          tokenUri: https://kauth.kakao.com/oauth/token
          userInfoUri: https://kapi.kakao.com/v2/user/me
          userNameAttribute: id